import { getCollection, getEntry } from 'astro:content'

export const docsPages = await getCollection('docs')
export const callouts = await getCollection('callouts')

export const aliasedDocsPages = await getCollection('docs', ({ data }) => {
  return data.aliases !== undefined
})

export function getCalloutByName(name: string) {
  return getEntry('callouts', name)
}

// Auto-generate sidebar from docs content structure
export function getAutoGeneratedSidebar() {
  const groups = new Map<string, { title: string; pages: { title: string; id: string }[] }>()

  // Group pages by their directory
  for (const page of docsPages) {
    const parts = page.id.split('/')
    if (parts.length >= 2) {
      const groupSlug = parts[0]
      const groupTitle = groupSlug
        .split('-')
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' ')

      if (!groups.has(groupSlug)) {
        groups.set(groupSlug, { title: groupTitle, pages: [] })
      }

      const group = groups.get(groupSlug)!
      group.pages.push({ title: page.data.title, id: page.id })
    }
  }

  // Convert to array and sort groups by their slug for consistent ordering
  return Array.from(groups.entries())
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([, group]) => group)
}
