// swift-tools-version:5.9

// Do not edit directly, this file was generated by packages/tokens/build/swift-package.js
// from chassis.build in packages/tokens/package.json: one library for every brand of every
// app with an iOS platform. Write it again with `pnpm tokens:swift-package`.

import PackageDescription

let package = Package(
    name: "ChassisTokens",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "ChassisTokensDemoChassis", targets: ["ChassisTokensDemoChassis"]),
        .library(name: "ChassisTokensDemoSinefil", targets: ["ChassisTokensDemoSinefil"])
    ],
    targets: [
        .target(
            name: "ChassisTokensDemoChassis",
            path: "packages/tokens/dist/ios/demo/chassis",
            resources: [.process("Icons.xcassets")]
        ),
        .target(
            name: "ChassisTokensDemoSinefil",
            path: "packages/tokens/dist/ios/demo/sinefil",
            resources: [.process("Icons.xcassets")]
        )
    ]
)
